#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avery_Weigh
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WIWEB_AveryDB_New")]
	public partial class DataClasses2DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses2DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["AveryDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblRFIDCARDDATA> tblRFIDCARDDATAs
		{
			get
			{
				return this.GetTable<tblRFIDCARDDATA>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblRFIDCARDDATA")]
	public partial class tblRFIDCARDDATA
	{
		
		private int _Id;
		
		private string _RFIDCARDNO;
		
		private string _RFIDTAGUID;
		
		private System.Nullable<int> _TripId;
		
		private System.Nullable<int> _TripType;
		
		private System.Nullable<bool> _IsMultiProduct;
		
		private string _GateEntryNo;
		
		private string _TruckNo;
		
		private string _MaterialCode;
		
		private string _MaterialName;
		
		private string _MaterialCalssificationCode;
		
		private string _MaterialClassificationName;
		
		private string _SupplierCode;
		
		private string _SupplierName;
		
		private string _TransporterCode;
		
		private string _TransporterName;
		
		private string _PackingCode;
		
		private string _PackingName;
		
		private System.Nullable<int> _PackingQty;
		
		private string _ChallanNo;
		
		private System.Nullable<System.DateTime> _ChallanDate;
		
		private string _ChallanWeight;
		
		private string _PONo;
		
		private System.Nullable<System.DateTime> _PODate;
		
		private string _POMaterials;
		
		private string _Remarks;
		
		private string _WEIGHSTATUS;
		
		private System.Nullable<bool> _RFIDCARDENABLED;
		
		public tblRFIDCARDDATA()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RFIDCARDNO", DbType="NVarChar(MAX)")]
		public string RFIDCARDNO
		{
			get
			{
				return this._RFIDCARDNO;
			}
			set
			{
				if ((this._RFIDCARDNO != value))
				{
					this._RFIDCARDNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RFIDTAGUID", DbType="NVarChar(MAX)")]
		public string RFIDTAGUID
		{
			get
			{
				return this._RFIDTAGUID;
			}
			set
			{
				if ((this._RFIDTAGUID != value))
				{
					this._RFIDTAGUID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TripId", DbType="Int")]
		public System.Nullable<int> TripId
		{
			get
			{
				return this._TripId;
			}
			set
			{
				if ((this._TripId != value))
				{
					this._TripId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TripType", DbType="Int")]
		public System.Nullable<int> TripType
		{
			get
			{
				return this._TripType;
			}
			set
			{
				if ((this._TripType != value))
				{
					this._TripType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsMultiProduct", DbType="Bit")]
		public System.Nullable<bool> IsMultiProduct
		{
			get
			{
				return this._IsMultiProduct;
			}
			set
			{
				if ((this._IsMultiProduct != value))
				{
					this._IsMultiProduct = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GateEntryNo", DbType="NVarChar(MAX)")]
		public string GateEntryNo
		{
			get
			{
				return this._GateEntryNo;
			}
			set
			{
				if ((this._GateEntryNo != value))
				{
					this._GateEntryNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruckNo", DbType="NVarChar(MAX)")]
		public string TruckNo
		{
			get
			{
				return this._TruckNo;
			}
			set
			{
				if ((this._TruckNo != value))
				{
					this._TruckNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaterialCode", DbType="NVarChar(MAX)")]
		public string MaterialCode
		{
			get
			{
				return this._MaterialCode;
			}
			set
			{
				if ((this._MaterialCode != value))
				{
					this._MaterialCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaterialName", DbType="NVarChar(MAX)")]
		public string MaterialName
		{
			get
			{
				return this._MaterialName;
			}
			set
			{
				if ((this._MaterialName != value))
				{
					this._MaterialName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaterialCalssificationCode", DbType="NVarChar(MAX)")]
		public string MaterialCalssificationCode
		{
			get
			{
				return this._MaterialCalssificationCode;
			}
			set
			{
				if ((this._MaterialCalssificationCode != value))
				{
					this._MaterialCalssificationCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaterialClassificationName", DbType="NVarChar(MAX)")]
		public string MaterialClassificationName
		{
			get
			{
				return this._MaterialClassificationName;
			}
			set
			{
				if ((this._MaterialClassificationName != value))
				{
					this._MaterialClassificationName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierCode", DbType="NVarChar(MAX)")]
		public string SupplierCode
		{
			get
			{
				return this._SupplierCode;
			}
			set
			{
				if ((this._SupplierCode != value))
				{
					this._SupplierCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierName", DbType="NVarChar(MAX)")]
		public string SupplierName
		{
			get
			{
				return this._SupplierName;
			}
			set
			{
				if ((this._SupplierName != value))
				{
					this._SupplierName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransporterCode", DbType="NVarChar(MAX)")]
		public string TransporterCode
		{
			get
			{
				return this._TransporterCode;
			}
			set
			{
				if ((this._TransporterCode != value))
				{
					this._TransporterCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransporterName", DbType="NVarChar(MAX)")]
		public string TransporterName
		{
			get
			{
				return this._TransporterName;
			}
			set
			{
				if ((this._TransporterName != value))
				{
					this._TransporterName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PackingCode", DbType="NVarChar(MAX)")]
		public string PackingCode
		{
			get
			{
				return this._PackingCode;
			}
			set
			{
				if ((this._PackingCode != value))
				{
					this._PackingCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PackingName", DbType="NVarChar(MAX)")]
		public string PackingName
		{
			get
			{
				return this._PackingName;
			}
			set
			{
				if ((this._PackingName != value))
				{
					this._PackingName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PackingQty", DbType="Int")]
		public System.Nullable<int> PackingQty
		{
			get
			{
				return this._PackingQty;
			}
			set
			{
				if ((this._PackingQty != value))
				{
					this._PackingQty = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChallanNo", DbType="NVarChar(MAX)")]
		public string ChallanNo
		{
			get
			{
				return this._ChallanNo;
			}
			set
			{
				if ((this._ChallanNo != value))
				{
					this._ChallanNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChallanDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ChallanDate
		{
			get
			{
				return this._ChallanDate;
			}
			set
			{
				if ((this._ChallanDate != value))
				{
					this._ChallanDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChallanWeight", DbType="NVarChar(MAX)")]
		public string ChallanWeight
		{
			get
			{
				return this._ChallanWeight;
			}
			set
			{
				if ((this._ChallanWeight != value))
				{
					this._ChallanWeight = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PONo", DbType="NVarChar(MAX)")]
		public string PONo
		{
			get
			{
				return this._PONo;
			}
			set
			{
				if ((this._PONo != value))
				{
					this._PONo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PODate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PODate
		{
			get
			{
				return this._PODate;
			}
			set
			{
				if ((this._PODate != value))
				{
					this._PODate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POMaterials", DbType="NVarChar(MAX)")]
		public string POMaterials
		{
			get
			{
				return this._POMaterials;
			}
			set
			{
				if ((this._POMaterials != value))
				{
					this._POMaterials = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="NVarChar(MAX)")]
		public string Remarks
		{
			get
			{
				return this._Remarks;
			}
			set
			{
				if ((this._Remarks != value))
				{
					this._Remarks = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WEIGHSTATUS", DbType="NVarChar(MAX)")]
		public string WEIGHSTATUS
		{
			get
			{
				return this._WEIGHSTATUS;
			}
			set
			{
				if ((this._WEIGHSTATUS != value))
				{
					this._WEIGHSTATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RFIDCARDENABLED", DbType="Bit")]
		public System.Nullable<bool> RFIDCARDENABLED
		{
			get
			{
				return this._RFIDCARDENABLED;
			}
			set
			{
				if ((this._RFIDCARDENABLED != value))
				{
					this._RFIDCARDENABLED = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
